language: python3.6
install: skip

sudo: required

branches:
  only:
    - test_compss
    - /^release-.*/

services:
  - docker
env:
  global:
    - REGISTRY_USER=compss
    - secure: ""
    - TEST_CASSANDRA_VERSION=3.11.6

before_script:
    - source launch_cassandra.sh
    - docker build --tag emebemb/dislib_hecuba_compss_production:0.4 .
    - docker run -it --network cassandra_bridge -d --name dislib emebemb/dislib_hecuba_compss_production:0.4


#script: "docker exec -e CONTACT_NAMES='cassandra_container' -e NODE_PORT=9042 dislib /dislib/run_tests.sh"
script: "docker exec -e CONTACT_NAMES='cassandra_container' -e NODE_PORT=9042 dislib runcompss --pythonpath='/usr/local/lib/python3.6/dist-packages/Hecuba-0.1.3.post1-py3.6-linux-x86_64.egg/' --python_interpreter=python3  --classpath=/hecuba/storageAPI/storageItf/target/StorageItf-1.0-jar-with-dependencies.jar  --storage_conf='/dislib/storage_conf.cfg' /dislib/tests/test_hecuba.py &> >(tee output.log)"
#after_script:
#  - docker images
#  - docker exec dislib /dislib/bin/print_tests_logs.sh
#
#before_deploy:
#  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
#  - docker tag bscwdc/dislib bscwdc/dislib:latest
#deploy:
#  provider: script
#  script: docker push bscwdc/dislib:latest
#  on:
#    branch: master


